version: '3.8'

services:
  postgres:
    container_name: courses_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=courses
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: